Ticket #24: Homepage Background Shapes
BobaTalks/internship-tracker pull request #106
Opened 2023-05-01 04:09 UTC by razlze

## Description
#### What is the purpose of your change?
- adding abstract geometric shapes into the homepage background

#### What areas of the application does this change impact? (changes API, folder structure, etc)
- added a styles folder in the components folder so I could use media queries on the images' css for responsiveness

#### What features/fixes are deferred/not handled in this PR?
-

## Checklist
- [ ] Adds unit tests
- [ ] Has a work item linked to the PR

2023-05-01 05:18 UTC, jwu910 requested changes
Just a comment about code pattern, everything else looking good

2023-05-01 05:18 UTC, jwu910 commented on client/src/components/styles/backgroundShapes.module.css
It'd be preferable, imo, to stick to the existing patterns for styling with MUI's sx props if possible. Introducing css modules shifts away from the styling pattern already established here

2023-05-01 05:30 UTC, razlze commented on client/src/components/styles/backgroundShapes.module.css
the problem is that i cant use the material UI sx props on the image component since it's not a material UI component. Im not sure how else to implement breakpoints other than media queries (which i can only do in an external CSS file)

2023-05-01 05:33 UTC, michachan commented on client/src/components/styles/backgroundShapes.module.css
Check this out: https://stackoverflow.com/questions/61263669/does-material-ui-have-an-image-component

2023-05-01 05:34 UTC, razlze commented on client/src/components/styles/backgroundShapes.module.css
oh cool! i'll try that thanks

2023-05-01 05:42 UTC, jwu910 commented on client/src/components/styles/backgroundShapes.module.css
Thanks for sharing michael, yeah @razlze, the MUI team has covered quite a few use cases we'd run into already. If we run into any complexity, by default checking if MUI already does _it_ is a great first step

2023-05-01 05:49 UTC, razlze commented on client/src/components/styles/backgroundShapes.module.css
for sure! will do so in the future - thanks for sharing :)

2023-05-02 01:51 UTC, jwu910 approved these changes

2023-05-02 04:45 UTC, merged

2023-05-08 03:20 UTC, jwu910 commented
@all-contributors please add @razlze for code