feat: Error Page
BobaTalks/internship-tracker pull request #113
Opened 2023-05-03 04:13 UTC by JennaXiao3

resolves #94 

## Description
#### What is the purpose of your change?
- create an Error Page 

#### What areas of the application does this change impact? (changes API, folder structure, etc)
-

#### What features/fixes are deferred/not handled in this PR?
-

## Checklist
- [ ] Adds unit tests
- [ ] Has a work item linked to the PR

2023-05-03 04:32 UTC, jwu910 requested changes
Looks good, just a couple comments for some files that snuck in

2023-05-03 04:32 UTC, jwu910 commented on client/src/contexts/FilterContext.js
Was this file accidentally committed? Doesn't seem related to this work

2023-05-03 04:32 UTC, jwu910 commented on client/src/contexts/AuthContext.js
Same comment, accidentally committed these? If we can let's keep the PRs scoped to the work, in case we need to ever revert commits, we won't accidentally remove some other critical functionality

2023-05-04 19:25 UTC, JennaXiao3 commented on client/src/contexts/FilterContext.js
oh oops yeah that was an accident

2023-05-05 01:36 UTC, JennaXiao3 commented
@jwu910 ready for re-review!

2023-05-05 03:24 UTC, jwu910 approved these changes

2023-05-05 03:24 UTC, merged