Add scraping functionality for Meta
BobaTalks/internship-tracker pull request #129
Opened 2023-05-17 07:23 UTC by lilyxmeng

## Description
#### What is the purpose of your change?
Add scraping code for Meta.

#### What areas of the application does this change impact? (changes API, folder structure, etc)
scraper/main.py

#### What features/fixes are deferred/not handled in this PR?
The code worked previously until it randomly started opening the page and saying I was not logged in -- do we want to create a random account to login with to ensure we don't run into this issue during deployment? In that case, I would have to look further into how to enter the login for a page via selenium.

## Checklist

2023-05-17 13:52 UTC, jwu910 commented
@lilyxmeng Can you rebase on to bobatalks(upstream)/main ? All of the commits from your other branch are present here

I recommend also spending time to get more familiar with Git and version control, it will be incredibly helpful get used to writing meaningful commit messages and building that habit now, makes reading and understanding changes and the intention behind changes easier. 

Easy way to remember is to write in the imperative mood. In your head you can say "if merged, this commit will:" and the following statement can be your commit message.

2023-05-17 14:01 UTC, jwu910 requested changes
Was this ready for review btw? I saw you mentioned it stopped working.

I suggest you gather details about this and communicate with the group chat to try and get some help and collaborate to find a solution, maybe someone else may have an idea as to why this is unable to scrape correctly

2023-05-17 16:16 UTC, lilyxmeng commented on scraper/main.py
> +    containers = driver.find_elements("xpath", "//div[@class='_6g3g x8y0a91 x7z1be2 xngnso2 xeqmlgx xo1l8bm xeqr9p9 x1e096f4']")
I'm not sure, all the classes on the page look randomly generated.

2023-06-02 23:13 UTC, a-camarillo commented on scraper/main.py
> +    containers = driver.find_elements("xpath", "//div[@class='_6g3g x8y0a91 x7z1be2 xngnso2 xeqmlgx xo1l8bm xeqr9p9 x1e096f4']")
@jwu910 I just took a look at this and the class names look pretty much the same(randomly generated?). The divs containing basic career information we do need do have the same class name "x1ypdohk" but I'm not sure how consistent we can consider this   
![image](https://github.com/BobaTalks/internship-tracker/assets/58638902/e5e125f8-80f8-400d-a4c1-dd62e00d7441)

2023-06-02 23:24 UTC, jwu910 commented on scraper/main.py
> +    containers = driver.find_elements("xpath", "//div[@class='_6g3g x8y0a91 x7z1be2 xngnso2 xeqmlgx xo1l8bm xeqr9p9 x1e096f4']")
I would want to bet that these are just namespaced and generated. I would not rely on them as consistent selectors. Can we check a level or two up to find something consistent and generic? 

The goal is to identify patterns that lead us to the data we want right?

Like is `div[role=link]` as a direct descendant of whatever is above that going to be unique enough to get us the data we need?

2023-06-02 23:30 UTC, a-camarillo commented on scraper/main.py
> +    containers = driver.find_elements("xpath", "//div[@class='_6g3g x8y0a91 x7z1be2 xngnso2 xeqmlgx xo1l8bm xeqr9p9 x1e096f4']")
I don't think the levels above are any better than what we currently have. There is a div with `id=careersContentContainer` but that is for the entire page element containing the career divs. Anything in between is seemingly generated.
![image](https://github.com/BobaTalks/internship-tracker/assets/58638902/f33b4372-341b-47b4-8a94-9869f5cea15a)

2023-06-02 23:55 UTC, jwu910 commented on scraper/main.py
> +    containers = driver.find_elements("xpath", "//div[@class='_6g3g x8y0a91 x7z1be2 xngnso2 xeqmlgx xo1l8bm xeqr9p9 x1e096f4']")
Is this structure the same for every job posting?

Cause if the constant is the ID, we technically could build out the selector with elements up to the div with the matching role right?

2023-06-03 00:16 UTC, a-camarillo commented on scraper/main.py
> +    containers = driver.find_elements("xpath", "//div[@class='_6g3g x8y0a91 x7z1be2 xngnso2 xeqmlgx xo1l8bm xeqr9p9 x1e096f4']")
ID is the constant for the page but each posting is shown by the `class="x1ypdohk"`, hopefully this screenshot isn't too small but for each job posting are more inner divs of generated classes to get the info we want. I suppose we can still use these class names to get the info we want but we will still lack the certainty we want

![image](https://github.com/BobaTalks/internship-tracker/assets/58638902/0bf00b2c-357a-4569-b0cc-a26f6454e76c)

2023-06-03 03:04 UTC, jwu910 commented on scraper/main.py
> +    containers = driver.find_elements("xpath", "//div[@class='_6g3g x8y0a91 x7z1be2 xngnso2 xeqmlgx xo1l8bm xeqr9p9 x1e096f4']")
could this be something like 

`div#careersContentContainer > div > div > div:nth-child(2) > div:nth-child(3)` or something similar?

2023-06-03 03:04 UTC, jwu910 commented on scraper/main.py
> +    containers = driver.find_elements("xpath", "//div[@class='_6g3g x8y0a91 x7z1be2 xngnso2 xeqmlgx xo1l8bm xeqr9p9 x1e096f4']")
@lilyxmeng thoughts?

2023-06-06 04:04 UTC, lilyxmeng commented on scraper/main.py
> +    containers = driver.find_elements("xpath", "//div[@class='_6g3g x8y0a91 x7z1be2 xngnso2 xeqmlgx xo1l8bm xeqr9p9 x1e096f4']")
I'll test something like this out and let you know of any changes.

2023-06-06 15:26 UTC, jwu910 commented on scraper/main.py
> +    containers = driver.find_elements("xpath", "//div[@class='_6g3g x8y0a91 x7z1be2 xngnso2 xeqmlgx xo1l8bm xeqr9p9 x1e096f4']")
Sounds good!

Was skimming over some articles to research a little and there were some mention of running the web drivers in headless mode as well, is that something we're already doing? Idk if its going to solve any of the current issues, but supposedly helpful when working with scraping SPAs at least

2023-06-24 16:47 UTC, jwu910 commented
Will be addressed in another PR.

CC: @a-camarillo

2023-06-24 16:47 UTC, closed without merging