141/generate filter options
BobaTalks/internship-tracker pull request #192
Opened 2024-06-02 18:37 UTC by razlze

## Description
#### What is the purpose of your change?
- generate search results based on the filters applied by the user 

#### What areas of the application does this change impact? (changes API, folder structure, etc)
- adds filtering logic within the SearchResultPage component

#### What features/fixes are deferred/not handled in this PR?
-

## Checklist
- [ ] Adds unit tests
- [ ] Has a work item linked to the PR

2024-08-11 01:43 UTC, victoriatran17 approved these changes

2024-08-13 00:01 UTC, victoriatran17 approved these changes

2024-08-13 01:18 UTC, JennaXiao3 requested changes

2024-08-13 01:18 UTC, JennaXiao3 commented on client/src/pages/SearchResultsPage.jsx
> +        if (key === 'remote') {
imo i think putting all this in a switch statement is cleaner

2024-08-13 01:18 UTC, JennaXiao3 commented on client/src/pages/SearchResultsPage.jsx
> +    });
I would move this to helper.js (u can rename the file to something better)

2024-08-13 01:26 UTC, JennaXiao3 commented on client/src/utils/api.js
> +// };
can be deleted

2024-08-26 21:08 UTC, merged