[TASK-56] Internship Tag
BobaTalks/internship-tracker pull request #84
Opened 2023-04-16 22:21 UTC by aqvilala

## Description
#### What is the purpose of your change?
- Implements internship tag component as per the updated Figma and #56 

#### What areas of the application does this change impact? (changes API, folder structure, etc)
- Adds a new component 

#### What features/fixes are deferred/not handled in this PR?
- N/A

## Checklist
- [ ] Adds unit tests
- [ ] Has a work item linked to the PR

2023-04-17 16:52 UTC, jwu910 requested changes
nice job on this PR, just two changes to make and we could be good to go. Are there screenshots of this from your local testing we can take a look at as well?

2023-04-17 16:52 UTC, jwu910 commented on client/src/components/InternshipTag.jsx
> +        <props.icon />
If we're passing an element into the props for this, we could destructure it from props first and then render it with the <> like a component

```jsx
const { icon: Icon } = props
// or 
const Icon = props.icon

// and then 

<Box>
  <Icon />
</Box> 
```

2023-04-17 16:52 UTC, jwu910 commented on client/src/components/InternshipTag.jsx
> +    <>
If we're returning a single element `Box` here, the fragment is unnecessary and we can remove it.

2023-04-21 13:15 UTC, jwu910 commented
Let us know if you need any support with this @aqvilala

2023-04-22 04:11 UTC, michachan commented on client/src/components/InternshipTag.jsx
> +  let theme = useTheme();
prefer const for variables not redefined

2023-04-29 20:40 UTC, jwu910 commented
@aqvilala Checking in again, any support we can provide with this work? If you need to pass this on, let us know so we can keep it moving. Thanks

2023-05-02 20:00 UTC, aqvilala commented
<img width="207" alt="image" src="https://user-images.githubusercontent.com/84333848/235772561-93cff4ef-e386-46cc-ae5c-300258ca4cc5.png">

Here's what the tag looks like on my local! I've made the changes and updated the PR

2023-05-02 20:16 UTC, jwu910 approved these changes
Nice, thanks!

2023-05-02 21:27 UTC, merged